name: Linter

on: [pull_request, push]

jobs:
  run-linters:
    name: Run linters
    runs-on: self-hosted

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Set up Node.js
        uses: nschloe/action-cached-lfs-checkout@v1
#        uses: actions/setup-node@v2
#        with:
#          node-version: '16'
#          cache: 'yarn'
#          cache-dependency-path: yarn.lock
#      - run: if [ ! -x "$(command -v yarn)" ]; then npm install -g yarn; fi

      - name: Version information
        run: echo "node $(node --version)"; echo "yarn $(yarn --version)"

      - name: Install dependencies
        run: |
          yarn cache clean --all
          yarn install
        env:
          CI: true

      - name: Lint
        run: yarn lint
