name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    name: Run tests
    runs-on: self-hosted

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: download contracts
        run: |
          cd $GITHUB_WORKSPACE/scripts/simapp/contracts
          rm checksums.sha256 hackatom.wasm ibc_reflect.wasm
          sh download.sh
          cd $GITHUB_WORKSPACE

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - run: if [ ! -x "$(command -v yarn)" ]; then npm install -g yarn; fi

      - name: Version information
        run: echo "node $(node --version)"; echo "yarn $(yarn --version)"

      - name: Install dependencies
        run: |
          yarn cache clean --all
          yarn install

      - name: Build
        run: yarn build

      - name: start simd
        run: CI= $GITHUB_WORKSPACE/scripts/simapp/start.sh

      - name: init contract on simd
        run: $GITHUB_WORKSPACE/scripts/simapp/init.sh

      - name: Unit Test Stargate
        run: |
          cd $GITHUB_WORKSPACE/packages/stargate
          SIMAPP_ENABLED=true yarn run test

      - name: Unit Test Cosmwasm-stargate
        run: |
          cd $GITHUB_WORKSPACE/packages/cosmwasm-stargate
          WASMD_ENABLED=true yarn run test
